export interface ResourceItem {
    english: string;
    local: string;
    category?: string;
    unit?: string;
}

export const GROCERIES_LIST: ResourceItem[] = [
    { "english": "Turmeric Powder", "local": "ಅರಿಶಿನ ಪುಡಿ", "category": "Groceries" },
    { "english": "Chilly Powder", "local": "ಖಾರದ ಪುಡಿ", "category": "Groceries" },
    { "english": "Sambar Powder", "local": "ಸಾಂಬಾರ್ ಪುಡಿ", "category": "Groceries" },
    { "english": "Rasam Powder", "local": "ರಸಂ ಪುಡಿ", "category": "Groceries" },
    { "english": "Pepper Powder", "local": "ಮೆಣಸಿನ ಪುಡಿ", "category": "Groceries" },
    { "english": "Jeera Powder", "local": "ಜೀರೆಗೆ ಪುಡಿ", "category": "Groceries" },
    { "english": "Coriander Powder", "local": "ಧನಿಯಾ ಪುಡಿ", "category": "Groceries" },
    { "english": "Fenugreek Powder", "local": "ಮೆಂತ್ಯ ಪುಡಿ", "category": "Groceries" },
    { "english": "Garam Masala", "local": "ಗರಂ ಮಸಾಲ", "category": "Groceries" },
    { "english": "Cinnamon Cloves", "local": "ಚಕ್ಕೆ ಲವಂಗ", "category": "Groceries" },
    { "english": "Garlic", "local": "ಬೆಳ್ಳುಳ್ಳಿ", "category": "Vegetables" },
    { "english": "Ginger", "local": "ಶುಂಠಿ", "category": "Vegetables" },
    { "english": "Mustard", "local": "ಸಾಸಿವೆ", "category": "Groceries" },
    { "english": "Jeera", "local": "ಜೀರೆ", "category": "Groceries" },
    { "english": "Fenugreek", "local": "ಮೆಂತ್ಯ", "category": "Groceries" },
    { "english": "Poppy Seeds", "local": "ಗಸಗಸೆ", "category": "Groceries" },
    { "english": "Cardamom", "local": "ಏಲಕ್ಕಿ", "category": "Groceries" },
    { "english": "Cloves", "local": "ಲವಂಗ", "category": "Groceries" },
    { "english": "Cinnamon", "local": "ಚಕ್ಕೆ", "category": "Groceries" },
    { "english": "Baking Soda", "local": "ಅಡುಗೆ ಸೋಡಾ", "category": "Groceries" },
    { "english": "Saffron Colour", "local": "ಕೇಸರಿ ಬಣ್ಣ", "category": "Groceries" },
    { "english": "Chatny Powder (Gurellu)", "local": "ಚಟ್ನಿ ಪೌಡರ್ (ಗುರಳ್ಳು)", "category": "Groceries" },
    { "english": "Black Gram Dhal", "local": "ಉದ್ದಿನ ಬೇಳೆ", "category": "Groceries" },
    { "english": "Bengal Gram Dhal", "local": "ಕಡಲೆ ಬೇಳೆ", "category": "Groceries" },
    { "english": "Green Gram Dhal", "local": "ಹೆಸರು ಬೇಳೆ", "category": "Groceries" },
    { "english": "Toor Dhal", "local": "ತೊಗರಿ ಬೇಳೆ", "category": "Groceries" },
    { "english": "Fried Gram", "local": "ಹುರಿಗಡಲೆ", "category": "Groceries" },
    { "english": "Bengal Gram", "local": "ಕಡಲೆ ಕಾಳು", "category": "Groceries" },
    { "english": "Green Gram", "local": "ಹೆಸರು ಕಾಳು", "category": "Groceries" },
    { "english": "Groundnut Seeds", "local": "ಕಡಲೆಕಾಯಿ ಬೀಜ", "category": "Groceries" },
    { "english": "Arecanut Powder", "local": "ಅಡಿಕೆ ಪುಡಿ", "category": "Groceries" },
    { "english": "Chickpeas", "local": "ಚಣಾದಳೆ", "category": "Groceries" },
    { "english": "Small Bengal Gram", "local": "ಕಡಲೆ ಬೇಳೆ ಸಣ್ಣ", "category": "Groceries" },
    { "english": "Wheat Flour", "local": "ಗೋಧಿ ಹಿಟ್ಟು", "category": "Groceries" },
    { "english": "Ragi Flour", "local": "ರಾಗಿ ಹಿಟ್ಟು", "category": "Groceries" },
    { "english": "Maida", "local": "ಮೈದಾ ಹಿಟ್ಟು", "category": "Groceries" },
    { "english": "Gram Flour", "local": "ಕಡಲೆ ಹಿಟ್ಟು", "category": "Groceries" },
    { "english": "Rice Flour", "local": "ಅಕ್ಕಿ ಹಿಟ್ಟು", "category": "Groceries" },
    { "english": "Chiroti Soji", "local": "ಚಿರೋಟಿ ರವೆ", "category": "Groceries" },
    { "english": "Medium Soji", "local": "ಮಧ್ಯಮ ರವೆ", "category": "Groceries" },
    { "english": "Bansi Soji", "local": "ಬನ್ಸಿ ರವೆ", "category": "Groceries" },
    { "english": "Uppittu Soji", "local": "ಉಪ್ಪಿಟ್ಟು ರವೆ", "category": "Groceries" },
    { "english": "Jowar Flour", "local": "ಜೋಳ ಹಿಟ್ಟು", "category": "Groceries" },
    { "english": "Maize Flour", "local": "ಜೋಳದ ಹಿಟ್ಟು", "category": "Groceries" },
    { "english": "Jaggery", "local": "ಬೆಲ್ಲ", "category": "Groceries" },
    { "english": "Ginger Jaggery", "local": "ಶುಂಠಿ ಬೆಲ್ಲ", "category": "Groceries" },
    { "english": "Liquid Jaggery", "local": "ಲಿಕ್ವಿಡ್ ಬೆಲ್ಲ", "category": "Groceries" },
    { "english": "Honey", "local": "ಜೇನುತುಪ್ಪ", "category": "Groceries" },
    { "english": "Sugar", "local": "ಸಕ್ಕರೆ", "category": "Groceries" },
    { "english": "Molasses", "local": "ಕಾಕಂಬಿ", "category": "Groceries" },
    { "english": "Chocolate Sugar", "local": "ಚಾಕ್ಲೇಟ್ ಸಕ್ಕರೆ", "category": "Groceries" },
    { "english": "Ghee", "local": "ತುಪ್ಪ", "category": "Dairy" },
    { "english": "Brand Meals Ghee", "local": "ಬೆಣ್ಣೆ ಕಾಯಿಸಿದ ತುಪ್ಪ(ನಂದಿನಿ)", "category": "Dairy" },
    { "english": "Choroli Ghee", "local": "ಚೊರೊಲಿ ತುಪ್ಪ", "category": "Dairy" },
    { "english": "Panner Ghee", "local": "ಪನ್ನೀರು ತುಪ್ಪ", "category": "Dairy" },
    { "english": "Liquid Cooking Medium", "local": "ಲಿಕ್ವಿಡ್ ಕುಕ್ಕಿಂಗ್ ಮೀಡಿಯಂ", "category": "Groceries" },
    { "english": "Refined Oil (Sun Flower)", "local": "ರಿಫೈನ್ಡ್ ಎಣ್ಣೆ (ಸನ್ ಫ್ಲವರ್)", "category": "Groceries" },
    { "english": "Groundnut Oil", "local": "ಕಡಲೆಕಾಯಿ ಎಣ್ಣೆ", "category": "Groceries" },
    { "english": "Coconut Oil", "local": "ತೆಂಗಿನ ಎಣ್ಣೆ", "category": "Groceries" },
    { "english": "Sesame Oil", "local": "ಎಳ್ಳೆಣ್ಣೆ", "category": "Groceries" },
    { "english": "Pooja Oil", "local": "ದೀಪದ ಎಣ್ಣೆ", "category": "Groceries" },
    { "english": "Pooja Ghee", "local": "ಪೂಜಾ ತುಪ್ಪ", "category": "Groceries" },
    { "english": "Soyabean Oil", "local": "ಸೋಯಾಬೀನ್ ಎಣ್ಣೆ", "category": "Groceries" },
    { "english": "Tomato", "local": "ಟೊಮ್ಯಾಟೊ", "category": "Vegetables" },
    { "english": "Onion", "local": "ಈರುಳ್ಳಿ", "category": "Vegetables" },
    { "english": "Potato", "local": "ಆಲೂಗಡ್ಡೆ", "category": "Vegetables" },
    { "english": "Carrot", "local": "ಕ್ಯಾರೆಟ್", "category": "Vegetables" },
    { "english": "Beans", "local": "ಬೀನ್ಸ್", "category": "Vegetables" },
    { "english": "Cauliflower", "local": "ಹೂಕೋಸು", "category": "Vegetables" },
    { "english": "Cabbage", "local": "ಎಲೆಕೋಸು", "category": "Vegetables" },
    { "english": "Mangalore Cucumber", "local": "ಸೌತೆಕಾಯಿ (ಮಂಗಳೂರು)", "category": "Vegetables" },
    { "english": "Sambar Cucumber", "local": "ಸೌತೆಕಾಯಿ (ಸಾಂಬಾರ್)", "category": "Vegetables" },
    { "english": "Pumpkin", "local": "ಕುಂಬಳಕಾಯಿ", "category": "Vegetables" },
    { "english": "Ash Gourd", "local": "ಬೂದುಗುಂಬಳ", "category": "Vegetables" },
    { "english": "Ridge Gourd", "local": "ಹೀರೆಕಾಯಿ", "category": "Vegetables" },
    { "english": "Bitter Gourd", "local": "ಹಾಗಲಕಾಯಿ", "category": "Vegetables" },
    { "english": "Ivy Gourd", "local": "ತೊಂಡೆಕಾಯಿ", "category": "Vegetables" },
    { "english": "Brinjal", "local": "ಬದನೆಕಾಯಿ", "category": "Vegetables" },
    { "english": "Drumstick", "local": "ನುಗ್ಗೆಕಾಯಿ", "category": "Vegetables" },
    { "english": "Ladies Finger", "local": "ಬೆಂಡೆಕಾಯಿ", "category": "Vegetables" },
    { "english": "Radish", "local": "ಮೂಲಂಗಿ", "category": "Vegetables" },
    { "english": "Kohlrabi", "local": "ಗಡ್ಡೆಕೋಸು", "category": "Vegetables" },
    { "english": "Green Chillies", "local": "ಹಸಿ ಮೆಣಸಿನಕಾಯಿ", "category": "Vegetables" },
    { "english": "Coriander Leaves", "local": "ಕೊತ್ತಂಬರಿ ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Curry Leaves", "local": "ಕರಿಬೇವು", "category": "Vegetables" },
    { "english": "Mint Leaves", "local": "ಪುದೀನಾ ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Palak Leaves", "local": "ಪಾಲಕ್ ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Dill Leaves", "local": "ಸಬ್ಬಸಿಗೆ ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Methi Leaves", "local": "ಮೆಂತ್ಯ ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Dantu Leaves", "local": "ದಂಟಿನ ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Green Peas", "local": "ಬಟಾಣಿ", "category": "Vegetables" },
    { "english": "Beet Root", "local": "ಬೀಟ್ರೂಟ್", "category": "Vegetables" },
    { "english": "Double Beans", "local": "ಡಬಲ್ ಬೀನ್ಸ್", "category": "Vegetables" },
    { "english": "Sweet Potato", "local": "ಗೆಣಸು", "category": "Vegetables" },
    { "english": "Cluster Beans", "local": "ಗೋರಿಕಾಯಿ", "category": "Vegetables" },
    { "english": "Raw Banana", "local": "ಬಾಳೆಕಾಯಿ", "category": "Vegetables" },
    { "english": "Banana Stem", "local": "ಬಾಳೆದಿಂಡು", "category": "Vegetables" },
    { "english": "Coconut", "local": "ತೆಂಗಿನಕಾಯಿ", "category": "Fruits" },
    { "english": "Lemon", "local": "ನಿಂಬೆ ಹಣ್ಣು", "category": "Fruits" },
    { "english": "Capsicum", "local": "ಶಿಮ್ಲಾ ಮೆಣಸಿನಕಾಯಿ", "category": "Vegetables" },
    { "english": "Snake Gourd", "local": "ಪಡವಲಕಾಯಿ", "category": "Vegetables" },
    { "english": "Drumstick Leaves", "local": "ನುಗ್ಗೆ ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Grapes", "local": "ದ್ರಾಕ್ಷಿ", "category": "Fruits" },
    { "english": "Apple", "local": "ಸೇಬು", "category": "Fruits" },
    { "english": "Banana", "local": "ಬಾಳೆ ಹಣ್ಣು", "category": "Fruits" },
    { "english": "Guava", "local": "ಸೀಬೆ ಹಣ್ಣು", "category": "Fruits" },
    { "english": "Papaya", "local": "ಪಪ್ಪಾಯ", "category": "Fruits" },
    { "english": "Watermelon", "local": "ಕಲ್ಲಂಗಡಿ", "category": "Fruits" },
    { "english": "Pineapple", "local": "ಅನಾನಸ್", "category": "Fruits" },
    { "english": "Pomegranate", "local": "ದಾಳಿಂಬೆ", "category": "Fruits" },
    { "english": "Mosambi", "local": "ಮೂಸಂಬಿ", "category": "Fruits" },
    { "english": "Sapota", "local": "ಸಪೋಟ", "category": "Fruits" },
    { "english": "Oranges", "local": "ಕಿತ್ತಳೆ ಹಣ್ಣು", "category": "Fruits" },
    { "english": "Strawberry", "local": "ಸ್ಟ್ರಾಬೆರ್ರಿ", "category": "Fruits" },
    { "english": "Kiwi", "local": "ಕಿವಿ", "category": "Fruits" },
    { "english": "Mango", "local": "ಮಾವಿನ ಹಣ್ಣು", "category": "Fruits" },
    { "english": "Cherry", "local": "ಚೆರ್ರಿ", "category": "Fruits" },
    { "english": "Milk", "local": "ಹಾಲು", "category": "Dairy" },
    { "english": "Curd", "local": "ಮೊಸರು", "category": "Dairy" },
    { "english": "Buttermilk", "local": "ಮಜ್ಜಿಗೆ", "category": "Dairy" },
    { "english": "Ice Cream", "local": "ಐಸ್ ಕ್ರೀಂ", "category": "Dairy" },
    { "english": "Madhur Milk", "local": "ಮಧುರ್ ಮಿಲ್ಕ್", "category": "Dairy" },
    { "english": "Milk Paneer", "local": "ಮಿಲ್ಕ್ ಪನ್ನೀರ್", "category": "Dairy" },
    { "english": "Kova", "local": "ಕೋವಾ", "category": "Dairy" },
    { "english": "Super Paal", "local": "ಸೂಪರ್ ಪಾಲ್", "category": "Dairy" },
    { "english": "Paneer Soda", "local": "ಪನ್ನೀರ್ ಸೋಡಾ", "category": "Dairy" },
    { "english": "Lassi", "local": "ಲಸ್ಸಿ", "category": "Dairy" },
    { "english": "Masala Tea", "local": "ಚಾಯ್ ಮಸಾಲಾ", "category": "Groceries" },
    { "english": "Coffee", "local": "ಕಾಫಿ", "category": "Groceries" },
    { "english": "Appalam", "local": "ಅಪ್ಪಳ", "category": "Groceries" },
    { "english": "Sandige", "local": "ಸಂಡಿಗೆ", "category": "Groceries" },
    { "english": "Rice Sandige", "local": "ಅಕ್ಕಿ ಸಂಡಿಗೆ", "category": "Groceries" },
    { "english": "Ragi Sandige", "local": "ರಾಗಿ ಸಂಡಿಗೆ", "category": "Groceries" },
    { "english": "Papad", "local": "ಹಪ್ಪಳ", "category": "Groceries" },
    { "english": "Kara Papad", "local": "ಖಾರಾ ಹಪ್ಪಳ", "category": "Groceries" },
    { "english": "Kara Boondi", "local": "ಖಾರಾ ಬೂಂದಿ", "category": "Groceries" },
    { "english": "Oil Papad (Spicy)", "local": "ಎಣ್ಣೆ ಹಪ್ಪಳ (ಖಾರ)", "category": "Groceries" },
    { "english": "Oil Papad (Plain)", "local": "ಎಣ್ಣೆ ಹಪ್ಪಳ (ಸಪ್ಪೆ)", "category": "Groceries" },
    { "english": "Chips", "local": "ಚಿಪ್ಸ್", "category": "Groceries" },
    { "english": "Sweets", "local": "ಮಿಠಾಯಿ", "category": "Groceries" },
    { "english": "Tea Leaf", "local": "ಟೀ ಪುಡಿ", "category": "Groceries" },
    { "english": "Coffee Powder", "local": "ಕಾಫಿ ಪುಡಿ", "category": "Groceries" },
    { "english": "Paper Cup", "local": "ಪೇಪರ್ ಕಪ್", "category": "Groceries" },
    { "english": "Plastic Cup", "local": "ಪ್ಲಾಸ್ಟಿಕ್ ಕಪ್", "category": "Groceries" },
    { "english": "Paper Plate", "local": "ಪೇಪರ್ ಪ್ಲೇಟ್", "category": "Groceries" },
    { "english": "Paper Glass", "local": "ಪೇಪರ್ ಲೋಟ", "category": "Groceries" },
    { "english": "Crayons Box", "local": "ಕ್ರಯಾನ್ಸ್ ಬಾಕ್ಸ್", "category": "Groceries" },
    { "english": "Pencil", "local": "ಪೆನ್ಸಿಲ್", "category": "Groceries" },
    { "english": "Eraser", "local": "ರಬ್ಬರ್", "category": "Groceries" },
    { "english": "Scale", "local": "ಸ್ಕೇಲ್", "category": "Groceries" },
    { "english": "Sharpener", "local": "ಶಾರ್ಪನರ್", "category": "Groceries" },
    { "english": "Fevicol", "local": "ಫೆವಿಕಾಲ್", "category": "Groceries" },
    { "english": "Chocolate", "local": "ಚಾಕೊಲೇಟ್", "category": "Groceries" },
    { "english": "Biscuit", "local": "ಬಿಸ್ಕತ್", "category": "Groceries" },
    { "english": "Silver Paper", "local": "ಸಿಲ್ವರ್ ಪೇಪರ್", "category": "Groceries" },
    { "english": "Drawing Paper", "local": "ಡ್ರಾಯಿಂಗ್ ಪೇಪರ್", "category": "Groceries" },
    { "english": "1/2 lt Water Bottle", "local": "1/2 ಲೀಟರ್ ವಾಟರ್ ಬಾಟಲ್", "category": "Groceries" },
    { "english": "Mug", "local": "ಮಗ್", "category": "Groceries" },
    { "english": "Fabric Soap", "local": "ಬಟ್ಟೆ ಸೋಪು", "category": "Groceries" },
    { "english": "Dish Soap", "local": "ಪಾತ್ರೆ ಸೋಪು", "category": "Groceries" },
    { "english": "Vim Liquid", "local": "ವಿಮ್ ಲಿಕ್ವಿಡ್", "category": "Groceries" },
    { "english": "Scrubber", "local": "ಸ್ಕ್ರಬ್ಬರ್", "category": "Groceries" },
    { "english": "Phenyl", "local": "ಫಿನೈಲ್", "category": "Groceries" },
    { "english": "Acid", "local": "ಆಸಿಡ್", "category": "Groceries" },
    { "english": "Soap Powder", "local": "ಸಾಬೂನು ಪುಡಿ", "category": "Groceries" },
    { "english": "Surf", "local": "ಸರ್ಫ್", "category": "Groceries" },
    { "english": "Rin Soap", "local": "ರಿನ್ ಸೋಪ್", "category": "Groceries" },
    { "english": "Body Soap", "local": "ಮೈ ಸೋಪು", "category": "Groceries" },
    { "english": "Plastic Cover", "local": "ಪ್ಲಾಸ್ಟಿಕ್ ಕವರ್", "category": "Groceries" },
    { "english": "Dust Bin", "local": "ಕಸದ ಬುಟ್ಟಿ", "category": "Groceries" },
    { "english": "Broom", "local": "ಪೊರಕೆ", "category": "Groceries" },
    { "english": "Wiper", "local": "ವೈಪರ್", "category": "Groceries" },
    { "english": "Odonil", "local": "ಓಡೋನಿಲ್", "category": "Groceries" },
    { "english": "G.T.C. Bottle", "local": "ಜಿ.ಟಿ.ಸಿ. ಬಾಟಲ್", "category": "Groceries" },
    { "english": "Mineral Water", "local": "ಶುದ್ಧ ಕುಡಿಯುವ ನೀರು", "category": "Groceries" },
    { "english": "Wet Tissue", "local": "ವೆಟ್ ಟಿಶ್ಯೂ", "category": "Groceries" },
    { "english": "Tissue Paper", "local": "ಟಿಶ್ಯೂ ಪೇಪರ್", "category": "Groceries" },
    { "english": "Kumkum", "local": "ಕುಂಕುಮ", "category": "Groceries" },
    { "english": "Camphor", "local": "ಕರ್ಪೂರ", "category": "Groceries" },
    { "english": "Rice", "local": "ಅಕ್ಕಿ", "category": "Groceries" },
    { "english": "Meals Rice (Cleaned)", "local": "ಊಟದ ಅಕ್ಕಿ", "category": "Groceries" },
    { "english": "Sona Masoori", "local": "ಕುಸುಬಲಕ್ಕಿ", "category": "Groceries" },
    { "english": "A Rice (Cleaned)", "local": "ರಾಜಮುಡಿ ಅಕ್ಕಿ", "category": "Groceries" },
    { "english": "Jeerige Samba Rice", "local": "ಜೀರಿಗೆ ಸಾಂಬಾ ಅಕ್ಕಿ", "category": "Groceries" },
    { "english": "Basmathi Rice", "local": "ಬಾಸುಮತಿ ಅಕ್ಕಿ", "category": "Groceries" },
    { "english": "Tamilnadu Boiled Rice", "local": "ತಮಿಳುನಾಡು ಬೊಲೆಡ್ ರೈಸ್", "category": "Groceries" },
    { "english": "Bennakallu Dhal", "local": "ಹೆಸರು ಬೇಳೆ", "category": "Groceries" },
    { "english": "Fried Greengram Dhal", "local": "ಕರಿದ ಹೆಸರು ಬೇಳೆ", "category": "Groceries" },
    { "english": "Cowgram", "local": "ಅವರೆ ಕಾಳು", "category": "Groceries" },
    { "english": "Avarebele", "local": "ಅವರೆ ಬೇಳೆ", "category": "Groceries" },
    { "english": "Friedgram Dhal", "local": "ಹುರಿಗಡಲೆ", "category": "Groceries" },
    { "english": "Greengram Dhal", "local": "ಹೆಸರು ಬೇಳೆ", "category": "Groceries" },
    { "english": "Green Dhal", "local": "ಹೆಸರು ಕಾಳು", "category": "Groceries" },
    { "english": "White Peas", "local": "ಬಿಳಿ ಬಟಾಣಿ", "category": "Groceries" },
    { "english": "Alasande", "local": "ಅಲಸಂದೆ", "category": "Groceries" },
    { "english": "Salem Chilies", "local": "ಸೇಲಂ ಮೆಣಸಿನಕಾಯಿ (ಗುಂಡು)", "category": "Groceries" },
    { "english": "Byadagi chilies", "local": "ಬ್ಯಾಡಗಿ ಮೆಣಸಿನಕಾಯಿ", "category": "Groceries" },
    { "english": "Coriander", "local": "ಕೊತ್ತಂಬರಿ", "category": "Groceries" },
    { "english": "Cumin Seeds", "local": "ಜೀರಿಗೆ", "category": "Groceries" },
    { "english": "Pepper", "local": "ಮೆಣಸು", "category": "Groceries" },
    { "english": "Mentya", "local": "ಮೆಂತ್ಯ", "category": "Groceries" },
    { "english": "Asafoetida", "local": "ಇಂಗು", "category": "Groceries" },
    { "english": "White Gingelly", "local": "ಬಿಳಿ ಎಳ್ಳು", "category": "Groceries" },
    { "english": "Black Gingelly", "local": "ಕರಿ ಎಳ್ಳು", "category": "Groceries" },
    { "english": "Salt", "local": "ಉಪ್ಪು", "category": "Groceries" },
    { "english": "Table Salt", "local": "ಪುಡಿ ಉಪ್ಪು", "category": "Groceries" },
    { "english": "Black Salt", "local": "ಕರಿ ಉಪ್ಪು", "category": "Groceries" },
    { "english": "Tamarind", "local": "ಹುಣಸೆ ಹಣ್ಣು", "category": "Groceries" },
    { "english": "Chakkuli Flour", "local": "ಚಕ್ಕುಲಿ ಹಿಟ್ಟು", "category": "Groceries" },
    { "english": "Urid Flour", "local": "ಉದ್ದಿನ ಹಿಟ್ಟು (ವಡಾಪುಡಿ)", "category": "Groceries" },
    { "english": "Arroott flour", "local": "ಆ್ಯರೊರೂಟ್ ಹಿಟ್ಟು", "category": "Groceries" },
    { "english": "White Soji", "local": "ಬಿಳಿ ರವೆ", "category": "Groceries" },
    { "english": "Red Soji", "local": "ಕೆಂಪು ರವೆ", "category": "Groceries" },
    { "english": "Broken Wheat", "local": "ದಪ್ಪ ಗೋಧಿ ನುಚ್ಚು", "category": "Groceries" },
    { "english": "Uppumavu Soji", "local": "ಉಪ್ಪಿಟ್ಟು ರವೆ", "category": "Groceries" },
    { "english": "(Idli) Boiled Rice", "local": "ಇಡ್ಲಿ ಅಕ್ಕಿ ತರಿ ", "category": "Groceries" },
    { "english": "Beaten Rice", "local": "ಅವಲಕ್ಕಿ (ದಪ್ಪ/ತೆಳು)", "category": "Groceries" },
    { "english": "Rava Rice Flake", "local": "ಅಕ್ಕಿ ಅವಲಕ್ಕಿ (ಗಟ್ಟಿ)", "category": "Groceries" },
    { "english": "Boora Sugar", "local": "ಬೂರಾ ಸಕ್ಕರೆ", "category": "Groceries" },
    { "english": "Soda (Drinking)", "local": "ಸೋಡಾ (ಕುಡಿಯುವುದು)", "category": "Groceries" },
    { "english": "Yeast", "local": "ಈಸ್ಟ್", "category": "Groceries" },
    { "english": "Lime Salt", "local": "ನಿಂಬು ಉಪ್ಪು", "category": "Groceries" },
    { "english": "Washing Powder (Nirma)", "local": "ವಾಷಿಂಗ್ ಪೌಡರ್ (ನಿರ್ಮಾ)", "category": "Groceries" },
    { "english": "Macroni", "local": "ಮ್ಯಾಕ್ರೋನಿ", "category": "Groceries" },
    { "english": "Rusk Powder/ Biscuit", "local": "ರಸ್ಕ್ ಪೌಡರ್ / ಬಿಸ್ಕತ್", "category": "Groceries" },
    { "english": "Jaljeera / Shajeera", "local": "ಜೀರಿಗೆ ಸೋಡ / ಶಜೀರಾ", "category": "Groceries" },
    { "english": "Cinnamon Bark", "local": "ದಾಲ್ಚಿನ್ನಿ ಚಕ್ಕೆ", "category": "Groceries" },
    { "english": "Marati Moggu", "local": "ಮರಾಠಿ ಮೊಗ್ಗು", "category": "Groceries" },
    { "english": "Cloves Leaf", "local": "ಲವಂಗದ ಎಲೆ", "category": "Groceries" },
    { "english": "Nut Meg", "local": "ಜಾಕಾಯಿ", "category": "Groceries" },
    { "english": "Japathre", "local": "ಜಾಪತ್ರೆ", "category": "Groceries" },
    { "english": "Pineapple Flower", "local": "ಅನಾನಸ್ ಹೂ", "category": "Groceries" },
    { "english": "Green Colour", "local": "ಗ್ರೀನ್ ಕಲರ್", "category": "Groceries" },
    { "english": "Orange Colour", "local": "ಆರೆಂಜ್ ಕಲರ್", "category": "Groceries" },
    { "english": "Lemon Yellow Colour", "local": "ಲೆಮನ್ ಯೆಲ್ಲೊ ಕಲರ್", "category": "Groceries" },
    { "english": "Pista Colour", "local": "ಪಿಸ್ತಾ ಕಲರ್", "category": "Groceries" },
    { "english": "Rose Essence", "local": "ರೋಸ್ ಎಸೆನ್ಸ್", "category": "Groceries" },
    { "english": "Rose Water", "local": "ರೋಸ್ ವಾಟರ್", "category": "Groceries" },
    { "english": "Pink Colour", "local": "ಪಿಂಕ್ ಕಲರ್", "category": "Groceries" },
    { "english": "Saffron", "local": "ಕುಂಕುಮ ಕೇಸರಿ", "category": "Groceries" },
    { "english": "Borneol Flakes", "local": "ಪಚ್ಚ ಕರ್ಪೂರ", "category": "Groceries" },
    { "english": "Badami Milk", "local": "ಬಾದಾಮಿ ಮಿಲ್ಕ್", "category": "Dairy" },
    { "english": "Jamoon Mix", "local": "ಜಾಮೂನ್ ಮಿಕ್ಸ್", "category": "Groceries" },
    { "english": "Almond Seeds", "local": "ಬಾದಾಮಿ ಬೀಜ", "category": "Groceries" },
    { "english": "Dry Grapes", "local": "ಒಣ ದ್ರಾಕ್ಷಿ", "category": "Groceries" },
    { "english": "Cashew Nuts", "local": "ಗೋಡಂಬಿ", "category": "Groceries" },
    { "english": "Cashew Nuts (Full)", "local": "ಗೋಡಂಬಿ (ಉಂಡೆ)", "category": "Groceries" },
    { "english": "Cashew (Baby)", "local": "ಬೇಬಿ ಗೋಡಂಬಿ", "category": "Groceries" },
    { "english": "Dry Coconut", "local": "ಒಣ ಕೊಬ್ಬರಿ", "category": "Groceries" },
    { "english": "Dry Anjura", "local": "ಒಣ ಅಂಜೂರ", "category": "Groceries" },
    { "english": "Mango Pickles", "local": "ಮಾವಿನಕಾಯಿ ಉಪ್ಪಿನಕಾಯಿ", "category": "Groceries" },
    { "english": "Kabab Masala", "local": "ಕಬಾಬ್ ಮಸಾಲ", "category": "Groceries" },
    { "english": "Palav Masala", "local": "ಪಲಾವ್ ಮಸಾಲ", "category": "Groceries" },
    { "english": "Pavbaji Masala", "local": "ಪಾವ್ ಬಾಜಿ ಮಸಾಲ", "category": "Groceries" },
    { "english": "Panipuri Masala", "local": "ಪಾನಿಪುರಿ ಮಸಾಲ", "category": "Groceries" },
    { "english": "Veniger", "local": "ವಿನಿಗರ್", "category": "Groceries" },
    { "english": "Gobi 65 Masala", "local": "ಗೋಬಿ 65 ಮಸಾಲ", "category": "Groceries" },
    { "english": "Meal Maker", "local": "ಮೀಲ್ ಮೇಕರ್", "category": "Groceries" },
    { "english": "Mushroom", "local": "ಮಶ್ರೂಮ್", "category": "Vegetables" },
    { "english": "Tasting Powder", "local": "ಟೇಸ್ಟಿಂಗ್ ಪೌಡರ್", "category": "Groceries" },
    { "english": "Tandoori Masala", "local": "ತಂದೂರಿ ಮಸಾಲ", "category": "Groceries" },
    { "english": "Chat Masala", "local": "ಚಾಟ್ ಮಸಾಲ", "category": "Groceries" },
    { "english": "Tomato / Nati", "local": "ಟೊಮೇಟೊ / ನಾಟಿ", "category": "Vegetables" },
    { "english": "W. Pumpkin", "local": "ಬಿಳಿ ಕುಂಬಳಕಾಯಿ", "category": "Vegetables" },
    { "english": "S. Pumpkin", "local": "ಸಿಹಿ ಕುಂಬಳಕಾಯಿ", "category": "Vegetables" },
    { "english": "Brinjal White (Long)", "local": "ಬಿಳಿ ಬದನೆಕಾಯಿ ಉದ್ದ", "category": "Vegetables" },
    { "english": "Plaintains", "local": "ಬಾಳೆಕಾಯಿ", "category": "Vegetables" },
    { "english": "Green Husk", "local": "ಸಿಪ್ಪೆ ಅವರೆ", "category": "Vegetables" },
    { "english": "Gherkins", "local": "ತೊಂಡೆಕಾಯಿ", "category": "Vegetables" },
    { "english": "Pot Herb", "local": "ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Jack Fruit", "local": "ಹಲಸಿನಕಾಯಿ", "category": "Fruits" },
    { "english": "Ash Fruit", "local": "ಬೂದುಗುಂಬಳ", "category": "Vegetables" },
    { "english": "White Raddish", "local": "ಬಿಳಿ ಮೂಲಂಗಿ", "category": "Vegetables" },
    { "english": "Cauli Flower", "local": "ಹೂ ಕೋಸು", "category": "Vegetables" },
    { "english": "Knoolkool", "local": "ನವಿಲು ಕೋಸು", "category": "Vegetables" },
    { "english": "Yam", "local": "ಸುವರ್ಣಗಡ್ಡೆ", "category": "Vegetables" },
    { "english": "Peace", "local": "ಬಟಾಣಿ", "category": "Vegetables" },
    { "english": "Plantain Leaves", "local": "ಬಾಳೆ ಎಲೆ", "category": "Vegetables" },
    { "english": "Onion (Ballary)", "local": "ಈರುಳ್ಳಿ (ಬಳ್ಳಾರಿ)", "category": "Vegetables" },
    { "english": "Salem Onion", "local": "ಸಾಂಬಾರ್ ಈರುಳ್ಳಿ", "category": "Vegetables" },
    { "english": "American Corn", "local": "ಅಮೇರಿಕನ್ ಕಾರ್ನ್", "category": "Vegetables" },
    { "english": "Betal Leaves", "local": "ವೀಳ್ಯದೆಲೆ", "category": "Vegetables" },
    { "english": "White Alasande", "local": "ಬಿಳಿ ಅಲಸಂದೆ", "category": "Groceries" },
    { "english": "Long Chillies", "local": "ಉದ್ದ ಮೆಣಸಿನಕಾಯಿ", "category": "Vegetables" },
    { "english": "Elekeere Soppu", "local": "ಎಲೆಕೋಸು", "category": "Vegetables" },
    { "english": "Cgikke Leaves", "local": "ಚಿಕ್ಕಿ ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Onion Leaves", "local": "ಈರುಳ್ಳಿ ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Etiku Bele", "local": "ಎಟಿಕುಹಿತಿಕಿದ ಬೆಳೆ", "category": "Groceries" },
    { "english": "Sabbakki Leaves", "local": "ಸಬ್ಬಕ್ಕಿ ಸೊಪ್ಪು", "category": "Vegetables" },
    { "english": "Kesu Leaves", "local": "ಕೆಸು ಎಲೆ", "category": "Vegetables" },
    { "english": "Red Raddish", "local": "ಕೆಂಪು ಮೂಲಂಗಿ", "category": "Vegetables" },
    { "english": "Baby Corn", "local": "ಬೇಬಿ ಕಾರ್ನ್", "category": "Vegetables" },
    { "english": "Davanagere Chillies", "local": "ದಾವಣಗೆರೆ ಮೆಣಸಿನಕಾಯಿ", "category": "Vegetables" },
    { "english": "Enagal Brinjal (Small)", "local": "ಎಣ್ಣೆಗಾಯಿ ಬದನೆಕಾಯಿ", "category": "Vegetables" },
    { "english": "Tiffin Leaves", "local": "ತಿಂಡಿ ಎಲೆ", "category": "Groceries" },
    { "english": "Dinner Leaves", "local": "ಊಟದ ಎಲೆ", "category": "Groceries" },
    { "english": "Banana (Yalakki)", "local": "ಬಾಳೆ ಹಣ್ಣು (ಏಲಕ್ಕಿ)", "category": "Fruits" },
    { "english": "Sweet Lime", "local": "ಮೂಸಂಬಿ", "category": "Fruits" },
    { "english": "Pomergranate", "local": "ದಾಳಿಂಬೆ", "category": "Fruits" },
    { "english": "Seedless Grapes", "local": "ಸೀಡ್ ಲೆಸ್ ದ್ರಾಕ್ಷಿ", "category": "Fruits" },
    { "english": "Cherry Fruit", "local": "ಚೆರ್ರಿ ಹಣ್ಣು", "category": "Fruits" },
    { "english": "Guava Fruit", "local": "ಸೀಬೆಕಾಯಿ", "category": "Fruits" },
    { "english": "Juice Mix", "local": "ಜ್ಯೂಸ್ ಮಿಕ್ಸ್", "category": "Groceries" },
    { "english": "Leache Fruit", "local": "ಲೀಚಿ ಹಣ್ಣು", "category": "Fruits" },
    { "english": "Australian Apple", "local": "ಆಸ್ಟ್ರೇಲಿಯನ್ ಆಪಲ್", "category": "Fruits" },
    { "english": "Australian Grapes", "local": "ಆಸ್ಟ್ರೇಲಿಯನ್ ಗ್ರೇಪ್ಸ್", "category": "Fruits" },
    { "english": "Kimi dates", "local": "ಕಿಮಿ ಡೇಟ್ಸ್", "category": "Fruits" },
    { "english": "Karbuz Fruit Seeds", "local": "ಕರ್ಬೂಜ ಹಣ್ಣಿನ ಬೀಜ", "category": "Groceries" },
    { "english": "Milk Kova", "local": "ಹಾಲು ಕೋವ", "category": "Dairy" },
    { "english": "Milk Panner", "local": "ಹಾಲು ಪನ್ನೀರ್", "category": "Dairy" },
    { "english": "Kalakan", "local": "ಕಲಾಕನ್", "category": "Dairy" },
    { "english": "Milk Cream", "local": "ಹಾಲು ಕ್ರೀಂ", "category": "Dairy" },
    { "english": "White Asafetida", "local": "ಬಿಳಿ ಇಂಗು", "category": "Groceries" },
    { "english": "Asafetida", "local": "ಇಂಗು", "category": "Groceries" },
    { "english": "Coriander seeds", "local": "ಧನಿಯಾ", "category": "Groceries" },
    { "english": "Chilli Powder ", "local": "ಮೆಣಸಿನಕಾಯಿ ಪುಡಿ", "category": "Groceries" },
    { "english": "Black Pepper Powder", "local": "ಕರಿ ಮೆಣಸು ಪುಡಿ", "category": "Groceries" },
    { "english": "Agarbatti", "local": "ಅಗರಬತ್ತಿ", "category": "Groceries" },
    { "english": "Red Colour", "local": "ರೆಡ್ ಕಲರ್ ", "category": "Groceries" },
    { "english": "Cow Ghee", "local": "ಬೆಣ್ಣೆ ಕಾಯಿಸಿದ ತುಪ್ಪ (ನಂದಿನಿ)", "category": "Dairy" },
    { "english": "Idli Kora cloth", "local": "ಇಡ್ಲಿ ಕೋರಾ ಬಟ್ಟೆ", "category": "Groceries" },
    { "english": "Leaves Cup", "local": "ದೊನ್ನೆ", "category": "Groceries" },
    { "english": "Gas", "local": "ಗ್ಯಾಸ್", "category": "Groceries" },
    { "english": "Mixi", "local": "ಮಿಕ್ಸಿ", "category": "Groceries" },
    { "english": "Dry tissues", "local": "ಡ್ರೈ ತಿಶ್ಯೂಸ್", "category": "Groceries" },
    { "english": "Wet tissues", "local": "ವೆಟ್ ತಿಶ್ಯೂಸ್ ", "category": "Groceries" },
    { "english": "Camphor", "local": "ಕರ್ಪೂರ", "category": "Groceries" },
    { "english": "Peni Soji", "local": "ಪೇಣಿ ರವೆ ", "category": "Groceries" },
    { "english": "White Pepper Powder", "local": "ಬಿಳಿ ಮೆಣಸು ಪುಡಿ", "category": "Groceries" },
    { "english": "Hydros", "local": "ಹೈಡ್ರೋಸ್", "category": "Groceries" },
    { "english": "Gulkan", "local": "ಗುಲ್ಕನ್", "category": "Groceries" },
    { "english": "Coconut Powder", "local": "ಕೊಕೊನಟ್ ಪೌಡರ್ ", "category": "Groceries" }
];

export const SHAMIYANA_LIST: ResourceItem[] = [
    { english: "Shamiyana (Canopy)", local: "ಶಾಮಿಯಾನ", unit: "Sq.ft" },
    { english: "Dining Table", local: "ಊಟದ ಟೇಬಲ್", unit: "Nos" },
    { english: "Chair", local: "ಚೇರ್", unit: "Nos" },
    { english: "Table Cloth", local: "ಟೇಬಲ್ ಕ್ಲಾತ್", unit: "Nos" },
    { english: "China Tent", local: "ಚೈನಾ ಟೆಂಟ್", unit: "Sq.ft" },
    { english: "Rubber Chairs", local: "ರಬ್ಬರ್ ಚೇರ್ಸ್", unit: "Nos" },
    { english: "Screen", local: "ಸ್ಕ್ರೀನ್", unit: "Nos" },
    { english: "Water Drum", local: "ನೀರಿನ ಡ್ರಂ", unit: "Nos" },
    { english: "Carpet/Rug", local: "ಜಮಖಾನ", unit: "Sq.ft" },
    { english: "Dining Floor Mat", local: "ಊಟದ ಜಮಖಾನ", unit: "Sq.ft" },
    { english: "Buffet Chafing Dish", local: "ಊಟದ ಬಾಪೆ", unit: "Nos" },
    { english: "Bucket", local: "ಬಕೆಟ್", unit: "Nos" },
    { english: "Ladle", local: "ಸೌಟು", unit: "Nos" },
    { english: "Rice Serving Spoon", local: "ಅನ್ನದ ಕೈ", unit: "Nos" },
    { english: "Wash Basin/Bowl", local: "ಬೇಸನ್", unit: "Nos" },
    { english: "Kettle", local: "ಕೆಟಲ್", unit: "Nos" },
    { english: "Jugs", local: "ಜಗ್ಗುಗಳು", unit: "Nos" },
    { english: "Steel Glass", local: "ಸ್ಟೀಲ್ ಗ್ಲಾಸ್", unit: "Nos" },
    { english: "Frying Pan/Wok", local: "ಬಾಂಡ್ಲಿ", unit: "Nos" },
    { english: "Mysore Pak Pan", local: "ಮೈಸೂರ್ ಪಾಕ್ ಬಾಂಡ್ಲಿ", unit: "Nos" },
    { english: "Jalebi/Jahangeer Pan", local: "ಜಹಾಂಗೀರ್ ಬಾಂಡ್ಲಿ", unit: "Nos" },
    { english: "Oil Strainer", local: "ಎಣ್ಣೆ ಜಾಲರಿ", unit: "Nos" },
    { english: "Hand Strainer", local: "ಕೈ ಜಾಲರಿ", unit: "Nos" },
    { english: "Boondi Maker", local: "ಬೂಂದಿ ಜಾಲರಿ", unit: "Nos" },
    { english: "Laddu Strainer", local: "ಲಾಡು ಜಾಲರಿ", unit: "Nos" },
    { english: "Large Wood Stirrer", local: "ಹುಟ್ಟು", unit: "Nos" },
    { english: "Pulao Vessel (Small)", local: "ಪಲಾವ್ ಪಾತ್ರೆ (ಚಿಕ್ಕದು)", unit: "Nos" },
    { english: "Pulao Vessel (Large)", local: "ಪಲಾವ್ ಪಾತ್ರೆ (ದೊಡ್ಡದು)", unit: "Nos" },
    { english: "Round Cooking Vessel (Small)", local: "ದಬರಿ (ಚಿಕ್ಕದು)", unit: "Nos" },
    { english: "Round Cooking Vessel (Large)", local: "ದಬರಿ (ದೊಡ್ಡದು)", unit: "Nos" },
    { english: "Deep Pot (Small)", local: "ಕೊಳಗ (ಚಿಕ್ಕದು)", unit: "Nos" },
    { english: "Deep Pot (Large)", local: "ಕೊಳಗ (ದೊಡ್ಡದು)", unit: "Nos" },
    { english: "Plates", local: "ತಟ್ಟೆಗಳು", unit: "Nos" },
    { english: "Paratha Plate", local: "ಪರೋಟ ತಟ್ಟೆ", unit: "Nos" },
    { english: "Rice Cooking Pot", local: "ಅನ್ನದ ತವಲೆ", unit: "Nos" },
    { english: "Dough Mixing Vessel", local: "ಹಿಟ್ಟಿನ ತವಲೆ", unit: "Nos" },
    { english: "Small Spatula", local: "ಕುರುಬಿ", unit: "Nos" },
    { english: "Pagoda Tent", local: "ಪಕೋಡ ಟೆಂಟ್", unit: "Sq.ft" },
    { english: "Gas Stove", local: "ಗ್ಯಾಸ್ ಸ್ಟೌವ್", unit: "Nos" },
    { english: "Grater Board", local: "ತುರಿಯೋ ಮಣೆ", unit: "Nos" },
    { english: "Low Wooden Seat", local: "ಸಾದಾ ಮಣೆ", unit: "Nos" },
    { english: "Steel Plate", local: "ಸ್ಟೀಲ್ ಪ್ಲೇಟ್", unit: "Nos" },
    { english: "Grinding Machine", local: "ರುಬ್ಬುವ ಯಂತ್ರ", unit: "Nos" },
    { english: "Petromax Lantern", local: "ಪೆಟ್ರೋಮ್ಯಾಕ್ಸ್", unit: "Nos" },
    { english: "Mysore Pak Tray", local: "ಮೈಸೂರ್ ಪಾಕ್ ಟ್ರೇ", unit: "Nos" },
    { english: "Small Bowls", local: "ಕಟೋರಿ", unit: "Nos" },
    { english: "Steel Spoon", local: "ಸ್ಟೀಲ್ ಸ್ಪೂನ್", unit: "Nos" },
    { english: "Generator", local: "ಜನರೇಟರ್", unit: "Shift" },
    { english: "Sieve/Sifter", local: "ಹೂಳ ಜರಡಿ", unit: "Nos" },
    { english: "Hand Bowl", local: "ಕೈ ಬಟ್ಟಲು", unit: "Nos" },
    { english: "Coconut Scraper", local: "ಒಣ ಕೊಬ್ಬರಿ ಮಣೆ", unit: "Nos" },
    { english: "Sliding Tent Walls", local: "ಸ್ಲೈಡ್ ವಾಲ್ಸ್", unit: "R.ft" },
    { english: "Holige Griddle", local: "ಹೋಳಿಗೆ ಹಂಚು", unit: "Nos" },
    { english: "Idli Steamer", local: "ಇಡ್ಲಿ ಪಾತ್ರೆ", unit: "Nos" },
    { english: "Coffee Filter", local: "ಕಾಫಿ ಫಿಲ್ಟರ್", unit: "Nos" },
    { english: "Cooling Mat", local: "ಕೂಲಿಂಗ್ ಮ್ಯಾಟ್", unit: "Sq.ft" },
    { english: "Rolling Pin", local: "ಲಟ್ಟಣಿಗೆ", unit: "Nos" },
    { english: "Measuring Unit (Seru)", local: "ಅಳತೆಯ ಸೇರು", unit: "Nos" },
    { english: "Pestle", local: "ಹೊಣಕೆ", unit: "Nos" },
    { english: "Carpet", local: "ಕಾರ್ಪೆಟ್", unit: "Sq.ft" },
    { english: "Wood Cutting Board", local: "ಜಿಪ್ಪ ಮಣೆ", unit: "Nos" },
    { english: "Knife", local: "ಚಾಕು", unit: "Nos" },
    { english: "Tarpaulin", local: "ತಾರ್ಪಲ್", unit: "Sq.ft" },
    { english: "L-Container", local: "ಎಲ್ ಡಬ್ಬ", unit: "Nos" },
    { english: "Rice Strainer", local: "ಅನ್ನ ಬಸಿಯುವುದು", unit: "Nos" },
    { english: "Sound Box", local: "ಸೌಂಡ್ ಬಾಕ್ಸ್", unit: "Set" },
    { english: "Focus Light", local: "ಫೋಕಸ್", unit: "Nos" },
    { english: "Serial Lights", local: "ಸೀರಿಯಲ್ ಸೆಟ್", unit: "Nos" },
    { english: "Ganesha Statue", local: "ಗಣೇಶ", unit: "Nos" },
    { english: "Round Table", local: "ರೌಂಡ್ ಟೇಬಲ್", unit: "Nos" },
    { english: "Grill", local: "ಗ್ರೀಲ್", unit: "Nos" },
    { english: "Tandoori Oven", local: "ತಂದೂರಿ ರೊಟ್ಟಿ ಡ್ರಂ", unit: "Nos" },
    { english: "Elephant Prop", local: "ಆನೆ", unit: "Nos" },
    { english: "Guardian Statues", local: "ರಕ್ಷಕರು", unit: "Nos" },
    { english: "Fountain", local: "ಫೌಂಟೇನ್", unit: "Nos" },
    { english: "Kaveri Water Girls", local: "ಕಾವೇರಿ ನೀರು ಹುಡುಗಿಯರು", unit: "Nos" },
    { english: "Wash Basin", local: "ವಾಷ್ ಬೇಷನ್", unit: "Nos" },
    { english: "Mudde Mixing Stick", local: "ಮುದ್ದೆ ಕೋಲು", unit: "Nos" },
    { english: "Iron Stove", local: "ಕಬ್ಬಿಣದ ಒಲೆ", unit: "Nos" },
    { english: "Peacock Prop", local: "ನವಿಲು", unit: "Nos" },
    { english: "Srinivasa-Padmavathi", local: "ಶ್ರೀನಿವಾಸ್ ಪದ್ಮವತಿ", unit: "Nos" },
    { english: "Scent/Mist Machine", local: "ಸೆಂಟ್ ಮಿಷನ್", unit: "Nos" },
    { english: "Sodium Lamp", local: "ಸೋಡಿಯಂ", unit: "Nos" },
    { english: "Stage", local: "ಸ್ಟೇಜ್", unit: "Sq.ft" },
    { english: "Mandap Chair", local: "ಮಂಟಪ ಚೇರ್", unit: "Nos" },
    { english: "Ritual Fire Pit", local: "ಹೋಮ ಕುಂಡ", unit: "Nos" },
    { english: "Bottled Water", local: "ಬಿಸ್ಲರಿ ವಾಟರ್", unit: "Nos" },
    { english: "Rumali Roti Pan", local: "ರೂಮಾಲಿ ಬಾಂಡ್ಲಿ", unit: "Nos" },
    { english: "Lamp Post", local: "ದೀಪಾವಳಿ ಕಂಬ", unit: "Nos" },
    { english: "Fan", local: "ಫ್ಯಾನ್", unit: "Nos" },
    { english: "Fire Pit Lamp", local: "ಹೋಮಕುಂಡದ ದೀಪ", unit: "Nos" },
    { english: "Welcome Lady Statue", local: "ವೆಲಕಂ ಲೇಡಿ", unit: "Nos" },
    { english: "Gas Cylinder", local: "ಸೀಲೆಂಡರ್", unit: "Nos" },
    { english: "VIP Chair", local: "ವಿ.ಐ.ಪಿ ಚೇರ್", unit: "Nos" },
    { english: "VIP Sofa", local: "ವಿ.ಐ.ಪಿ ಸೋಫ", unit: "Nos" },
    { english: "Chair Cover", local: "ಚೇರ್ ಕ್ಲಾತ್", unit: "Nos" },
    { english: "Hookah/Flower Hook Set", local: "ಹೂಕರ್ ಸೆಟ್", unit: "Set" },
    { english: "Wedding Set", local: "ವಧುವೆ ಸೆಟ್", unit: "Set" },
    { english: "Cleaning Staff", local: "ಕ್ಲೀನಿಂಗ್ ಜನ", unit: "Nos" },
    { english: "Drum Set (Music)", local: "ಟಮಟಿ ಸೆಟ್", unit: "Set" },
    { english: "Table Grill", local: "ಟೇಬಲ್ ಗ್ರೀಲ್", unit: "Nos" },
    { english: "Bed and Pillow", local: "ಹಾಸಿಗೆ ದಿಂಬು", unit: "Set" },
    { english: "Name Board", local: "ನೇಮ್ ಬೋರ್ಡ್", unit: "Nos" },
    { english: "Pearl Palanquin", local: "ಮುತ್ತಿನ ಪಲ್ಲಕ್ಕಿ", unit: "Nos" }
];

export const MENU_ITEMS_LIST: ResourceItem[] = [
    { english: "Idli", local: "ಇಡ್ಲಿ" },
    { english: "Vada", local: "ವಡೆ" },
    { english: "Sambar", local: "ಸಾಂಬಾರ್" },
    { english: "Chutney", local: "ಚಟ್ನಿ" },
    { english: "Kesari Bath", local: "ಕೇಸರಿ ಬಾತ್" },
    { english: "Rice Bath", local: "ರೈಸ್ ಬಾತ್" },
    { english: "White Rice", local: "ಬಿಳಿ ಅನ್ನ" },
    { english: "Rasam", local: "ರಸಂ" },
    { english: "Curd Rice", local: "ಮೊಸರು ಅನ್ನ" },
    { english: "Sweet", local: "ಸಿಹಿ" },
    { english: "Ice Cream", local: "ಐಸ್ ಕ್ರೀಮ್" },
    { english: "Chapathi", local: "ಚಪಾತಿ" },
    { english: "Palya", local: "ಪಲ್ಯ" },
    { english: "Kosambari", local: "ಕೋಸಂಬರಿ" },
    { english: "Papad", local: "ಹಪ್ಪಳ" },
    { english: "Pickle", local: "ಉಪ್ಪಿನಕಾಯಿ" }
];

export function autoCategorize(itemName: string): string {
    const name = itemName.toLowerCase();
    const vegKeywords = ['tomato', 'onion', 'potato', 'carrot', 'beans', 'cauliflower', 'cabbage', 'cucumber', 'pumpkin', 'gourd', 'brinjal', 'drumstick', 'ladies finger', 'radish', 'kohlrabi', 'chilli', 'leaves', 'peas', 'beet', 'sweet potato', 'banana stem', 'lemon', 'capsicum', 'plantain', 'vegetable', 'soppu'];
    const fruitKeywords = ['apple', 'banana', 'grapes', 'orange', 'mango', 'papaya', 'watermelon', 'pineapple', 'pomegranate', 'guava', 'strawberry', 'kiwi', 'cherry', 'sapota', 'mosambi', 'fruit'];
    const dairyKeywords = ['milk', 'curd', 'buttermilk', 'ice cream', 'paneer', 'kova', 'ghee', 'cream', 'butter', 'lassi', 'dairy', 'cheese', 'yogurt'];

    if (vegKeywords.some(k => name.includes(k))) return 'Vegetables';
    if (fruitKeywords.some(k => name.includes(k))) return 'Fruits';
    if (dairyKeywords.some(k => name.includes(k))) return 'Dairy';
    return 'Groceries';
}
